# Generated by ChatGPT
from django.db import migrations, models
import apps.candidates.models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "primary_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "primary_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "latest_company",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARSING", "Parsing"),
                            ("PARSED", "Parsed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.candidates.models.resume_upload_path),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARSING", "Parsing"),
                            ("PARSED", "Parsed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Extraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField(blank=True, default="")),
                ("fields_json", models.JSONField(default=dict)),
                ("confidences_json", models.JSONField(default=dict)),
                (
                    "model_name",
                    models.CharField(blank=True, default="heuristics", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="STARTED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extractions",
                        to="candidates.resume",
                    ),
                ),
            ],
        ),
    ]