# Generated by ChatGPT
from django.db import migrations, models
import apps.documents.models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PAN", "PAN"), ("AADHAAR", "Aadhaar")],
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ("mime_type", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("masked_number", models.CharField(blank=True, default="", max_length=32)),
                ("verified_flags_json", models.JSONField(default=dict)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS")],
                        default="EMAIL",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("WAITING", "Waiting"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("message_preview", models.TextField(blank=True, default="")),
                ("magic_token", models.CharField(blank=True, default="", max_length=128)),
                ("link_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("PORTAL", "Portal"), ("STAFF", "Staff")],
                        default="STAFF",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "aadhaar_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_aadhaar_submission",
                        to="documents.document",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_submissions",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "pan_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_pan_submission",
                        to="documents.document",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="documents.documentrequest",
                    ),
                ),
            ],
        ),
    ]